### ISSUE TITLE
ChangeStart parameter cancel changed to next

### ISSUE THREAD

**Issue by kevinkaos** [kelp404/capybara-router#141]
Hi kelp404, 
I have been using capybara-router for my project since 2019 and just wanted to know how to proceed with cancel() changing to next()?

For example, my user is not authorized should redirect to login page, with cancel I can simply cancel router action, but with next i have to redirect to destination then redirect back.

Please let me know as i am a fan of your custom router. Thank you.

**Comment by kelp404** [comment]
Thank you.
I think next() is better then cancel().

**Comment by kelp404** [comment]
Hello,

Thank you for the issue.
Sorry about the changing from `cancel()` to `next()`.
This changing is to solve call `cancel()` in the async function.

If you want to `cancel()` the changing in the current version, you just don't call `next()`.
Please call `next()` at all `ChangeStart` events when you want to do next steps.
